name: CI

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  verify:
    uses: ddtcorex/dsh-maestro-ci/.github/workflows/node-plugin.yml@33f1677f8c634c5386348f96c77d31a0e3bbadc4
